version: "3.9"

services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  app:
    build: ./app
    container_name: mqtt-report-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mqtt-broker
    command: >
      sh -c "sleep 10 && python -u main.py"
    environment:
      PYTHONUNBUFFERED: "1"
      MQTT_HOST: mqtt-broker
      MQTT_PORT: "1883"
      MQTT_USER: "Agrodigital"
      MQTT_PASS: "Eng2025@"
      MQTT_TOPICS: "silos/#"
      WHATSAPP_INSTANCE_ID: "instance148636"
      WHATSAPP_TOKEN: "01vo85agef4imw7a"
      WHATSAPP_TO: "+555591656011"      # n√∫mero destino
    volumes:
      - ./data:/data
